### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by sxjscience**
Fix the teaser image in the README

### CODE REVIEW

**Comment by gaurav71531** [comment]
This doesn't work either for Chrome and safari

**Comment by sxjscience** [comment]
I checked https://github.com/sxjscience/BOON and it works

**Comment by sxjscience** [comment]
@gaurav71531 would you be able to check again?

**Comment by gaurav71531** [comment]
Some issue with Chrome amd_64 for rendering png. But it is working on other machines.

**Pull request merged**
